### ISSUE TITLE
MultiGPU errors

### ISSUE THREAD

**Issue by ebartrum** [autonomousvision/projected_gan#44]
Thanks for the great repo and the congrats on the amazing paper!
Training is working fine for me with 1 GPU but I'm getting mysterious errors with >1 GPU. I'm not sure how to fix these. I'm using your recommended conda environment with  CUDA 11.3 . When running the pokemon expt with 2 GPUs I get the following std out:

```
Distributing across 2 GPUs...                                                                                                                                                               
Setting up training phases...                                                                                                                                                               
Exporting sample images...                                                                                                                                                                  
Traceback (most recent call last):                                                                                                                                                          
  File "/home/ed/Documents/repos/projected_gan/train.py", line 266, in <module>                                                                                                             
    main() # pylint: disable=no-value-for-parameter                                                                                                                                         
  File "/home/ed/.conda/envs/pg/lib/python3.9/site-packages/click/core.py", line 1137, in __call__                                                                                          
    return self.main(*args, **kwargs)                                                                                                                                                       
  File "/home/ed/.conda/envs/pg/lib/python3.9/site-packages/click/core.py", line 1062, in main                                                                                              
    rv = self.invoke(ctx)                                                                                                                                                                   
  File "/home/ed/.conda/envs/pg/lib/python3.9/site-packages/click/core.py", line 1404, in invoke                                                                                            
    return ctx.invoke(self.callback, **ctx.params)                                                                                                                                          
  File "/home/ed/.conda/envs/pg/lib/python3.9/site-packages/click/core.py", line 763, in invoke                                                                                             
    return __callback(*args, **kwargs)                                                                                                                                                      
  File "/home/ed/Documents/repos/projected_gan/train.py", line 252, in main                                                                                                                 
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)                                                                                                               
  File "/home/ed/Documents/repos/projected_gan/train.py", line 103, in launch_training                                                                                                      
    torch.multiprocessing.spawn(fn=subprocess_fn, args=(c, temp_dir), nprocs=c.num_gpus)                                                                                                    
  File "/home/ed/.conda/envs/pg/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn                                                                             
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')                                                                                                            
  File "/home/ed/.conda/envs/pg/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes                                                                   
    while not context.join():                                                                                                                                                               
  File "/home/ed/.conda/envs/pg/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 130, in join                                                                              
    raise ProcessExitedException(                                                                                                                                                           
torch.multiprocessing.spawn.ProcessExitedException: process 1 terminated with signal SIGABRT 
```

And the following error out:

```
terminate called after throwing an instance of 'c10::CUDAError'                                                                                  
  what():  CUDA error: the launch timed out and was terminated                                                                                                                       
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.                                                           
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.                                                                                      
Exception raised from create_event_internal at ../c10/cuda/CUDACachingAllocator.cpp:1211 (most recent call first):                          
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7fe48196fd62 in /home/ed/.conda/envs/pg/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1c4d3 (0x7fe481bd24d3 in /home/ed/.conda/envs/pg/lib/python3.9/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x1a2 (0x7fe481bd2ee2 in /home/ed/.conda/envs/pg/lib/python3.9/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0xa4 (0x7fe481959314 in /home/ed/.conda/envs/pg/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #4: std::vector<at::Tensor, std::allocator<at::Tensor> >::~vector() + 0x4a (0x7fe4de77a80a in /home/ed/.conda/envs/pg/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #5: c10d::ProcessGroupNCCL::barrier(c10d::BarrierOptions const&) + 0x9c6 (0x7fe4850be296 in /home/ed/.conda/envs/pg/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0xe86443 (0x7fe4def1a443 in /home/ed/.conda/envs/pg/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x2a544b (0x7fe4de33944b in /home/ed/.conda/envs/pg/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x15ff85 (0x55cf0df03f85 in /home/ed/.conda/envs/pg/bin/python)                                                                  
frame #9: _PyObject_MakeTpCall + 0x316 (0x55cf0deea986 in /home/ed/.conda/envs/pg/bin/python)                                          
frame #10: <unknown function> + 0x1a225a (0x55cf0df4625a in /home/ed/.conda/envs/pg/bin/python)                                                                      
frame #11: _PyEval_EvalFrameDefault + 0x11e1 (0x55cf0df85141 in /home/ed/.conda/envs/pg/bin/python)                                              
frame #12: <unknown function> + 0x259205 (0x55cf0dffd205 in /home/ed/.conda/envs/pg/bin/python)                                                                                      
frame #13: _PyEval_EvalFrameDefault + 0x4c92 (0x55cf0df88bf2 in /home/ed/.conda/envs/pg/bin/python)                                                                               
frame #14: <unknown function> + 0x139c70 (0x55cf0deddc70 in /home/ed/.conda/envs/pg/bin/python)                                                                                   
frame #15: _PyFunction_Vectorcall + 0x336 (0x55cf0df45596 in /home/ed/.conda/envs/pg/bin/python)                                                                                  
frame #16: _PyObject_Call + 0xb5 (0x55cf0df04335 in /home/ed/.conda/envs/pg/bin/python)                                                                                           
frame #17: _PyEval_EvalFrameDefault + 0x2d69 (0x55cf0df86cc9 in /home/ed/.conda/envs/pg/bin/python)                                                                               
frame #18: _PyFunction_Vectorcall + 0x19a (0x55cf0df453fa in /home/ed/.conda/envs/pg/bin/python)                                                                                  
frame #19: _PyObject_Call + 0x10b (0x55cf0df0438b in /home/ed/.conda/envs/pg/bin/python)                                                                                          
frame #20: _PyEval_EvalFrameDefault + 0x2d69 (0x55cf0df86cc9 in /home/ed/.conda/envs/pg/bin/python)                                                                               
frame #21: _PyFunction_Vectorcall + 0x19a (0x55cf0df453fa in /home/ed/.conda/envs/pg/bin/python)                                                                                  
frame #22: _PyObject_Call + 0x10b (0x55cf0df0438b in /home/ed/.conda/envs/pg/bin/python)                                                                                          
frame #23: _PyEval_EvalFrameDefault + 0x2d69 (0x55cf0df86cc9 in /home/ed/.conda/envs/pg/bin/python)                                                                                         
frame #24: _PyFunction_Vectorcall + 0x19a (0x55cf0df453fa in /home/ed/.conda/envs/pg/bin/python)                                                                                            
frame #25: _PyEval_EvalFrameDefault + 0x609 (0x55cf0df84569 in /home/ed/.conda/envs/pg/bin/python)                                                                                          
frame #26: <unknown function> + 0x139430 (0x55cf0dedd430 in /home/ed/.conda/envs/pg/bin/python)                                                                                             
frame #27: _PyFunction_Vectorcall + 0x336 (0x55cf0df45596 in /home/ed/.conda/envs/pg/bin/python)                                                                                            
frame #28: _PyEval_EvalFrameDefault + 0x609 (0x55cf0df84569 in /home/ed/.conda/envs/pg/bin/python)                                                                                          
frame #29: _PyFunction_Vectorcall + 0x19a (0x55cf0df453fa in /home/ed/.conda/envs/pg/bin/python)                                                                                            
frame #30: _PyEval_EvalFrameDefault + 0x3bc (0x55cf0df8431c in /home/ed/.conda/envs/pg/bin/python)                                                                                          
frame #31: <unknown function> + 0x139430 (0x55cf0dedd430 in /home/ed/.conda/envs/pg/bin/python)                                                                                             
frame #32: _PyFunction_Vectorcall + 0x336 (0x55cf0df45596 in /home/ed/.conda/envs/pg/bin/python)                                                                                            
frame #33: _PyEval_EvalFrameDefault + 0x11e1 (0x55cf0df85141 in /home/ed/.conda/envs/pg/bin/python)                                                                                         
frame #34: <unknown function> + 0x139430 (0x55cf0dedd430 in /home/ed/.conda/envs/pg/bin/python)                                                                                             
frame #35: _PyEval_EvalCodeWithName + 0x47 (0x55cf0dfc3517 in /home/ed/.conda/envs/pg/bin/python)                                                                                           
frame #36: PyEval_EvalCodeEx + 0x39 (0x55cf0dfc3559 in /home/ed/.conda/envs/pg/bin/python)                                                                                                  
frame #37: PyEval_EvalCode + 0x1b (0x55cf0dfc357b in /home/ed/.conda/envs/pg/bin/python)                                                                                                    
frame #38: <unknown function> + 0x251ec9 (0x55cf0dff5ec9 in /home/ed/.conda/envs/pg/bin/python)                                                                                             
frame #39: <unknown function> + 0x28cc04 (0x55cf0e030c04 in /home/ed/.conda/envs/pg/bin/python)                                                                                             
frame #40: PyRun_StringFlags + 0x9d (0x55cf0e03702d in /home/ed/.conda/envs/pg/bin/python)                                                                                                  
frame #41: PyRun_SimpleStringFlags + 0x3d (0x55cf0e03708d in /home/ed/.conda/envs/pg/bin/python)                                                                                            
frame #42: Py_RunMain + 0x25c (0x55cf0e03730c in /home/ed/.conda/envs/pg/bin/python)                                                                                                        
frame #43: Py_BytesMain + 0x39 (0x55cf0e037599 in /home/ed/.conda/envs/pg/bin/python)                                                                                                       
frame #44: __libc_start_main + 0xd5 (0x7fe4e0fceb25 in /usr/lib/libc.so.6)                                                                                                                  
frame #45: <unknown function> + 0x20c6b1 (0x55cf0dfb06b1 in /home/ed/.conda/envs/pg/bin/python)                                                                                             
                                                                                                                                                                                            
/home/ed/.conda/envs/pg/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 34 leaked semaphore objects to clean up at shutdown        
  warnings.warn('resource_tracker: There appear to be %d '
```

Any ideas on how to fix this?

**Comment by woctezuma** [comment]
As the error output shows, the launch timed out.

```
CUDA error: the launch timed out and was terminated                                                                                                                       
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.                                                           
For debugging consider passing CUDA_LAUNCH_BLOCKING=1. 
```

The error arises here, with an exception being raised as expected in the comment:

```python
    # Loop on join until it returns True or raises an exception.
    while not context.join():
        pass
```

in this function:

https://github.com/pytorch/pytorch/blob/60632a00fe6212159164d92ad69766925ab15c97/torch/multiprocessing/spawn.py#L170-L199

**Comment by ebartrum** [comment]
The code works with 1 GPU for each GPU! When running with 2 GPUs after passing CUDA_LAUNCH_BLOCKING=1, the std out became this:

```
Distributing across 2 GPUs...    
Setting up training phases...    
Exporting sample images...    
Traceback (most recent call last):    
  File "/home/ed/Documents/repos/projected_gan/train.py", line 266, in <module>    
    main() # pylint: disable=no-value-for-parameter    
  File "/home/ed/.conda/envs/pg/lib/python3.9/site-packages/click/core.py", line 1137, in __call__    
    return self.main(*args, **kwargs)    
  File "/home/ed/.conda/envs/pg/lib/python3.9/site-packages/click/core.py", line 1062, in main    
    rv = self.invoke(ctx)    
  File "/home/ed/.conda/envs/pg/lib/python3.9/site-packages/click/core.py", line 1404, in invoke    
    return ctx.invoke(self.callback, **ctx.params)    
  File "/home/ed/.conda/envs/pg/lib/python3.9/site-packages/click/core.py", line 763, in invoke    
    return __callback(*args, **kwargs)                
  File "/home/ed/Documents/repos/projected_gan/train.py", line 252, in main    
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)    
  File "/home/ed/Documents/repos/projected_gan/train.py", line 103, in launch_training    
    torch.multiprocessing.spawn(fn=subprocess_fn, args=(c, temp_dir), nprocs=c.num_gpus)    
  File "/home/ed/.conda/envs/pg/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn    
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')     
  File "/home/ed/.conda/envs/pg/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes    
    while not context.join():    
  File "/home/ed/.conda/envs/pg/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 150, in join    
    raise ProcessRaisedException(msg, error_index, failed_process.pid)    
torch.multiprocessing.spawn.ProcessRaisedException:    
                       
-- Process 1 terminated with the following error:    
Traceback (most recent call last):    
  File "/home/ed/.conda/envs/pg/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap    
    fn(i, *args)    
  File "/home/ed/Documents/repos/projected_gan/train.py", line 47, in subprocess_fn    
    training_loop.training_loop(rank=rank, **c)                                      
  File "/home/ed/Documents/repos/projected_gan/training/training_loop.py", line 258, in training_loop    
    torch.distributed.broadcast(__CUR_NIMG__, 0)    
  File "/home/ed/.conda/envs/pg/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1159, in broadcast    
    work = default_pg.broadcast([tensor], opts)    
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:45, unhandled cuda error, NCCL version 21.0.3    
ncclUnhandledCudaError: Call to CUDA function failed.   
```

**Comment by woctezuma** [comment]
We would need expertise of Axel there.

Maybe relevant:
- https://github.com/NVIDIA/nccl/issues/141
- https://github.com/pytorch/pytorch/issues/9163

**Comment by xl-sr** [comment]
hey :) i am pretty busy right now, so I am slow to respond currently. This seems to an issue unrelated to the PG codebase and more of a problem with your GPU/cuda setup. Do you have issues running the stylegan3 codebase (https://github.com/NVlabs/stylegan3)?

**Comment by ebartrum** [comment]
I'm getting similar errors when trying to run Stylegan3 training. I'll raise an issue on that repo!

**Comment by ebartrum** [comment]
OK I seem to have resolved this now. It seems the problem was caused by having an X session running during training. I hadn't realised this doesn't work! For some reason, training other models on all gpus with pytorch lightning while running an X session was fine. Hope someone else who has this problem comes across this issue!
